import { api } from "@/utils/api";
// import { useUser } from "@clerk/nextjs";
import { useSession } from "next-auth/react";

import { useState } from "react";
import { LoadingPage } from "./loading";

export const PostEditor = ({
  topicId,
  topicTitle,
}: {
  topicId?: string;
  topicTitle?: string;
}) => {
  // const { user, isLoaded: userLoaded, isSignedIn } = useUser();
  const { data: sessionData, status } = useSession();

  const { mutate, isLoading: isPosting } = api.analogy.create.useMutation({
    onSuccess: () => {
      setInput({
        title: "",
        description: "",
        topicId: "",
      });
      void ctx.analogy.getAll.invalidate();
    },
  });

  const [input, setInput] = useState({
    title: "",
    description: "",
    topicId: "",
  });

  const ctx = api.useContext();
  if (status === "loading") return <LoadingPage />;

  if (sessionData && !sessionData.user) {
    return <>Please sign in to post</>;
  } else {
    return (
      <>
        <form onSubmit={(e) => e.preventDefault()}>
          <div className="mx-auto my-5 mb-16 w-full max-w-[640px] rounded-[17px] border border-gray-200 bg-gray-50 transition-all hover:border-[#c1c1c1] focus:border-[#c1c1c1] dark:border-gray-600 dark:bg-gray-700">
            <div className="rounded-[17px] bg-white px-6 pt-6 dark:bg-gray-800">
              <label htmlFor="comment" className="sr-only">
                Add your analogy
              </label>
              <textarea
                id="comment"
                rows={4}
                className="w-full border-0 border-transparent bg-white px-0 text-sm text-[#2A2A2E] !outline-none focus:border-transparent focus:ring-0 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400"
                placeholder="Add your analogy ..."
                required
                value={input.description}
                onChange={(e) =>
                  setInput({
                    ...input,
                    description: e.target.value,
                  })
                }
                disabled={isPosting}
              ></textarea>
            </div>
            <div className="flex items-center justify-between border-t px-3 py-2 dark:border-gray-600">
              <div className="flex space-x-1 pl-0 sm:pl-2">
                <button
                  type="button"
                  className=" font-small inline-flex cursor-pointer select-none justify-center rounded p-2 text-xs text-gray-500 hover:bg-gray-100 hover:text-[#2A2A2E] dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                >
                  how to write markdown?
                </button>
              </div>
              <button
                // dont refresh the page on submit
                disabled={isPosting}
                onClick={() =>
                  mutate({
                    title: input.title,
                    description: input.description,
                    // a new cuid generated by the client
                    topicId: topicId ?? "",
                  })
                }
                type="submit"
                className="mx-1 my-1 inline-flex select-none justify-center rounded-[12px] border border-[#51320a43] bg-gradient-to-br from-[#e98908] to-[#ef6400] px-4 py-1.5 text-sm font-semibold text-white shadow-sm transition-all hover:shadow-md hover:brightness-125 focus:outline-none focus:ring-2 focus:ring-[#1d1d1d] focus:ring-offset-2"
              >
                Post analogy
              </button>
            </div>
          </div>
        </form>
      </>
    );
  }
};
